version: "3"

services:
  app:
    user: '${WWWUSER}:${WWWGROUP}'
    build:
      context: ./docker/php
      args:
        UID: "${WWWUSER}"
        GID: "${WWWGROUP}"
    ports:
      - "${HTTP_PORT:-127.0.0.1:8091}:8000"
    environment:
      APP_ENV: "${APP_ENV}"
      TZ: "Europe/Moscow"
    volumes:
      - ./:/var/www
      - ./docker/php/php.ini:/lib/php.ini
    entrypoint: "./run.sh"
    restart: always

#    links:
#      - mysql
#    depends_on:
#      - mysql
#
#  mysql:
#    restart: always
#    image: mysql:8.0
#    ports:
#      - "${MYSQL_PORT:-127.0.0.1:3306}:3306"
#    command: [
#      '--innodb_flush_log_at_trx_commit=2',
#    ]
#    volumes:
#      - mysql:/var/lib/mysql
#    environment:
#      MYSQL_DATABASE: "${DB_DATABASE}"
#      MYSQL_USER: "${DB_USERNAME}"
#      MYSQL_PASSWORD: "${DB_PASSWORD}"
#      MYSQL_ROOT_PASSWORD: "${DB_ROOT_PASSWORD}"
#      TZ: "Europe/Moscow"
#    healthcheck:
#      test: [ "CMD", "mysqladmin", "ping", "-p${DB_PASSWORD}" ]
#      retries: 3
#      timeout: 5s
#
#volumes:
#  mysql:
#    driver: local
